/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData back = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData check = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData delete = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData ptest = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData pgear = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData psimulate = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData ptrain = const IconData(0xe818, fontFamily: _kFontFam);
}
